
services:
  mongo:
    image: mongo:4.4
    container_name: fastapi-mongo
    ports:
      - "27017:27017" # Host:Container Port Mapping
    volumes:
      - mongo-data:/data/db # Persist MongoDB data
  backend:
    build:
      context: .       # Context is the root of the project
      dockerfile: app/Dockerfile
      #command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-config", "app/log_config.yml"]
    ports:
      - "8000:8000"  # Example port mapping 
    volumes:
      - ./app:/usr/src/app

volumes:
  mongo-data: # Named volume for persistent storage
